fix: wrap run cmd in an if statement

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -52,8 +52,12 @@ jobs:
             docker rm $(docker ps -aq --filter publish=4008) || true
 
             # Run new container
-            docker run -d \
-              -p 4008:3000 \
-              -e PUSHER_APP_KEY=${PUSHER_APP_KEY} \
-              ${{ secrets.DOCKER_HUB_USERNAME2 }}/atlp-devpulse-bn:latest
+            # wrap this in an if statement to check if the container is running
+            output=$( docker run -d --name devpulse-bn -p 4008:3000 ${{ secrets.DOCKER_HUB_USERNAME2 }}/atlp-devpulse-bn:latest )
+            echo "::set-output name=container_id::$output"
+            echo "Container ID: $output"
+            if [ -z "$output" ]; then
+              echo "Container failed to start"
+              exit 1
+            fi
 
